model:
  type: pyramid
  depth: 272
  alpha: 200
  bottleneck: True
dataset: cifar100
aug: rwaug_t
rwaug:
  n: 2

cutout: 16
batch: 256
epoch: 1800
lr: 0.2
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.00005

