model:
  type: resnet50
dataset: imagenet
aug: ohl
ohlaug:
  n: 2
cutout: 0
batch: 1024
epoch: 270  # 270
lr: 0.1
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 2
    epoch: 3
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  lars: False
  label_smoothing: 0.0