model:
  type: resnet50
dataset: imagenet
aug: ohl
randaug:
  N: 2
  M: 9

cutout: 0
batch: 128
epoch: 30  # 270
lr: 0.05
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  lars: False
  label_smoothing: 0.0
