model:
  type: resnet50
dataset: imagenet
aug: randaugment
randaug:
  N: 2
  M: 9

cutout: 0
batch: 1024
epoch: 180  # 270
lr: 0.1
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 4
    epoch: 3
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  lars: False
  label_smoothing: 0.0
