model:
  type: resnet18
dataset: reduced_imagenet
aug: ohl
randaug:
  N: 2
  M: 9

cutout: 0
batch: 256
epoch: 50 # 270
lr: 0.001
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  lars: False
  label_smoothing: 0.0
