model:
  type: resnet50
dataset: imagenet
aug: rwaug_t2
rwaug:
  n: 2
cutout: 0
batch: 512
epoch: 270  # 270
lr: 0.2
lr_schedule:
  type: 'resnet'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  lars: False
  label_smoothing: 0.0
