model:
  type: shakeshake26_2x96d
dataset: cifar100
aug: randaugment
randaug:
  N: 3
  M: 9

cutout: 16
batch: 128
epoch: 300
lr: 0.01
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
