model:
  type: shakeshake26_2x96d
dataset: cifar10
aug: rwaug_s
rwaug:
  n: 2
cutout: 16
batch: 128
epoch: 200
lr: 0.005
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
