model:
  type: wresnet28_10
dataset: cifar10
aug: rwaug_t
rwaug:
  n: 2
  mix: mixup
  mix_prob: 0.25
  alpha: 0.2
cutout: 16
batch: 128
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005