model:
  type: wresnet28_10
dataset: cifar10
aug: randaugment
randaug:
  N: 3
  M: 5
rwaug:
  n: 2
cutout: 16
batch: 128
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
