model:
  type: wresnet28_10
dataset: reduced_cifar10
aug: rwaug_s
rwaug:
  n: 2
cutout: 16
batch: 16
epoch: 50
lr: 0.001
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
