model:
  type: wresnet28_10
dataset: svhn
aug: rwaug_t
rwaug:
  n: 2
cutout: 16
batch: 256
epoch: 160
lr: 0.005
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
