model:
  type: wresnet28_10
dataset: svhn
aug: randaugment
randaug:
  N: 3
  M: 7    # from appendix

cutout: 16
batch: 128
epoch: 160
lr: 0.005
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
